### ISSUE TITLE
[Enhancement] Send new commands to clients

### ISSUE THREAD

**Issue by Ecconia** [Pieter12345/JavaLoader#5]
#### Issue:
Currently when new commands are added to a project the recompile is not able to add these to the players command registry.
This leads to the players not seeing the new command and even getting an error when typing it. It however perfectly works.

#### Possible fix:
Whenever JavaLoader detects, that a plugin added a command or removed one, or it loads/unloads a project with commands, it should call the method `syncCommands()` in the class `CraftServer`.
This method is private and needs to be accessed via reflection.
It creates a new list of all commands and sends that list to all players and new ##players.

#### Expected:
When adding a command into a JavaLoader project, and recompile this project, players can right away see this command in their tabcompletion (if its conditions are met).

**Comment by Ecconia** [comment]
Apparently we both forgot that a change of the aliases also has to be considered and updated.
Thus currently its not updating when only the aliases change.

Edit: How annoying, I cannot reopen this issue. Well I assume you get an email either way.

**Comment by Pieter12345** [comment]
@Ecconia This should be fixed in dc2a42caa5b4562248046cd5169a6146516658c3.
