### ISSUE TITLE
No java compiler available. This plugin requires a JDK to run on. Disabling plugin.

### ISSUE THREAD

**Issue by Gokborg** [Pieter12345/JavaLoader#7]
Problem
========
So I have been getting the error message "No java compiler available. This plugin requires a JDK to run on. Disabling plugin" when using the plugin on my server. Here is a picture of the stacktrace:
![errorJL](https://user-images.githubusercontent.com/31186380/81503139-fb397400-92af-11ea-8971-fd08aed8bb8a.JPG)

Reason
========
My path variable was pointing to the wrong Java executable. The server was running on JRE. My PATH variable was pointing to JRE and JDK in the wrong order.

What fixed it
========
I removed the JRE from the PATH variable. This allowed it to point to the JDK

What could have helped me
========
Maybe the error message could include "is the server running on JRE instead of JDK?" or "you have to run the server with JDK." 

P.S. @Ecconia found the reason for the stack trace.
"The project manager is not set in onEnable due to the error, which causes an NPE in onDisable."

**Comment by Pieter12345** [comment]
Thanks, your input is appreciated.
