### ISSUE TITLE
Using JDK 12 Java Loader fails to compile projects

### ISSUE THREAD

**Issue by Gokborg** [Pieter12345/JavaLoader#8]
The compile fails because the JavaLoader packages cannot be found in the project.

Using JDK 8 doesn't cause these issues.

**Comment by Pieter12345** [comment]
Thanks for the report. I can reproduce the issue using JDK 14.

### Problem
When compiling, JavaLoader passes the path to the JavaLoader jar to the Java compiler. It looks like the compiler on later Java versions no longer accepts the format I'm passing to it. Constructing this classpath happens here:
https://github.com/Pieter12345/JavaLoader/blob/master/src/main/java/io/github/pieter12345/javaloader/core/JavaProject.java#L180-L193

Note that the runtime environment is not affected by this bug (once compiled, even with a different version of Java, JavaLoader projects load properly. Only compilation is affected).

### Workaround
If you want to use a later version of Java with JavaLoader, then you can add `plugin JavaLoader` to `dependencies.txt` (which should be placed in the root of your JavaLoader project). This adds the same JavaLoader jar to the classpath, only its file path is in a different format, which later versions of the Java compiler accept.
